CREATE TABLE SREELATHA
(SID INT,SNAME VARCHAR(20)NOT NULL,AGE INT chECK(AGE>18),COURSE CHAR(3) DEFAULT 'MCA',PRIMARY KEY(SID));

SELECT
    *
FROM SREELATHA;

desc SREELATHA;

INSERT INTO SREELATHA VALUES(1,'BADRA',50,'MCA');

INSERT INTO SREELATHA VALUES(&SID,'&SNAME',&AGE,'&COURSE');

drop table Sreelatha;



